name: Brain Traduções
favicon: null
layout_spectrum: 0.42288
typography_spectrum: 0.56034
title: Brain Traduções
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1c62d1'
    - '#4b4b4b'
    - '#f7f7f5'
    - '#9a9b95'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
