name: Brain Traduções
favicon: null
layout_spectrum: 0.42288
typography_spectrum: 0.56034
title: Brain Traduções
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d0d0d0'
    - '#fc7f00'
    - '#fd3f05'
    - '#68524e'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
